<?php return array (
  'benfreke\\menumanager\\Plugin' => 'plugins/benfreke/menumanager/Plugin.php',
  'october\\demo\\Plugin' => 'plugins/october/demo/Plugin.php',
  'rahman\\faker\\Plugin' => 'plugins/rahman/faker/Plugin.php',
  'zainab\\simplecontact\\Plugin' => 'plugins/zainab/simplecontact/Plugin.php',
  'rainlab\\translate\\Plugin' => 'plugins/rainlab/translate/Plugin.php',
  'getright\\services\\Plugin' => 'plugins/getright/services/Plugin.php',
  'GetRight\\Services\\Providers\\ServiceRepositoryProvider' => 'plugins/getright/services/providers/ServiceRepositoryProvider.php',
  'RainLab\\Translate\\Classes\\Translator' => 'plugins/rainlab/translate/classes/Translator.php',
  'RainLab\\Translate\\Models\\Locale' => 'plugins/rainlab/translate/models/Locale.php',
  'RainLab\\Translate\\Classes\\LocaleMiddleware' => 'plugins/rainlab/translate/classes/LocaleMiddleware.php',
  'RainLab\\Translate\\Behaviors\\TranslatablePageUrl' => 'plugins/rainlab/translate/behaviors/TranslatablePageUrl.php',
  'RainLab\\Translate\\Classes\\EventRegistry' => 'plugins/rainlab/translate/classes/EventRegistry.php',
  'RainLab\\Translate\\Models\\Message' => 'plugins/rainlab/translate/models/Message.php',
  'BenFreke\\MenuManager\\Components\\Menu' => 'plugins/benfreke/menumanager/components/Menu.php',
  'BenFreke\\MenuManager\\Models\\Menu' => 'plugins/benfreke/menumanager/models/Menu.php',
  'RainLab\\Translate\\Classes\\TranslatableBehavior' => 'plugins/rainlab/translate/classes/TranslatableBehavior.php',
  'RainLab\\Translate\\Behaviors\\TranslatableModel' => 'plugins/rainlab/translate/behaviors/TranslatableModel.php',
);